name = "shorten-url"
main = "src/index.ts"
compatibility_date = "2025-01-21"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
API_KEY = "baccano"

[[kv_namespaces]]
binding = "KV"
id = "2d552022dbc74142a59afad474e08060"
preview_id = "fc8c79e887ec43238e103c93fae23e69"